In [2]:
# import libraries & setup plotting constants

import numpy as np
import numpy.linalg as la
import scipy.linalg as sla

# see https://docs.scipy.org/doc/numpy/reference/routines.linalg.html for linalg documentation

In [3]:
# Setup
print ('\nSetup')

A = np.array([[-3.,5.,7.],[2.,6.,4.],[0.,2.,8.]])
print ('\nA =\n',A)
print ('\nShape of A = ',np.shape(A))
n = np.shape(A)[0]
print ('\nDimensionality of A = ',n)

At = np.transpose(A)
print ('\nAt =\n',At)
print ('\nShape of At = ',np.shape(At))

B = np.array([4.,5.,6.])
B = B.reshape(3,1)
print ('\nB = \n',B)
print ('\nShape of B = ',np.shape(B))


Setup

A =
 [[-3.  5.  7.]
 [ 2.  6.  4.]
 [ 0.  2.  8.]]

Shape of A =  (3, 3)

Dimensionality of A =  3

At =
 [[-3.  2.  0.]
 [ 5.  6.  2.]
 [ 7.  4.  8.]]

Shape of At =  (3, 3)

B = 
 [[4.]
 [5.]
 [6.]]

Shape of B =  (3, 1)


In [4]:
# Matrix inverses

print ('\nMatrix Inverses')

invA = la.inv(A)
print ('\nA =\n',A)
print ('\nA^-1 =\n',invA)
print ('\nA * A^-1 (should be identity matrix) =\n',np.matmul(A , invA))
print ('\nA^-1 * A (should be identity matrix) =\n',np.matmul(invA , A))
print ('\n[(A^-1)^-1] - A (should be 0) = \n',la.inv(invA)-A)


Matrix Inverses

A =
 [[-3.  5.  7.]
 [ 2.  6.  4.]
 [ 0.  2.  8.]]

A^-1 =
 [[-0.23255814  0.15116279  0.12790698]
 [ 0.09302326  0.13953488 -0.15116279]
 [-0.02325581 -0.03488372  0.1627907 ]]

A * A^-1 (should be identity matrix) =
 [[ 1.00000000e+00  4.16333634e-17  8.32667268e-17]
 [-2.08166817e-16  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

A^-1 * A (should be identity matrix) =
 [[ 1.00000000e+00 -4.44089210e-16 -4.44089210e-16]
 [ 0.00000000e+00  1.00000000e+00  2.22044605e-16]
 [ 0.00000000e+00  5.55111512e-17  1.00000000e+00]]

[(A^-1)^-1] - A (should be 0) = 
 [[ 0.00000000e+00 -8.88178420e-16 -1.77635684e-15]
 [ 0.00000000e+00  1.77635684e-15  8.88178420e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]
